source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'CFNetworkEngine_Example' do
  pod 'CFNetworkEngine', :path => '../'

  target 'CFNetworkEngine_Tests' do
    inherit! :search_paths

    
  end
end
